---
abstract: 'Fork a process and read/write from it'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::Memory::Cycle: 1.04
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-IOLoop-ReadWriteFork
no_index:
  directory:
    - t
    - inc
requires:
  IO::Pty: 1.10
  Mojolicious: 4.30
resources:
  bugtracker: https://github.com/jhthorsen/mojo-ioloop-readwritefork/issues
  homepage: https://metacpan.org/release/Mojo-IOLoop-ReadWriteFork
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/mojo-ioloop-readwritefork
version: 0.02
