---
abstract: 'Fork a process and read/write from it'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::Memory::Cycle: 1.04
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-IOLoop-ReadWriteFork
no_index:
  directory:
    - t
    - inc
requires:
  IO::Pty: 1.10
  Mojolicious: 4.30
resources:
  bugtracker: https://github.com/jhthorsen/mojo-ioloop-readwritefork/issues
  homepage: https://github.com/jhthorsen/mojo-ioloop-readwritefork
  repository: https://github.com/jhthorsen/mojo-ioloop-readwritefork.git
version: 0.09
